'use strict';
const fs=require('node:fs');const path=require('node:path');
const {request,recordsFromPayload,first,stripHtml,splitPages,isNoMessage}=require('./common');
const URL='https://api.algotraffic.com/v3.0/TravelerInformationSystems?includeGeometry=true'; const PAGE='https://algotraffic.com/';
function saveDebug(text){if(!/^(?:1|true|yes)$/i.test(process.env.ALGO_DEBUG||''))return;const d=path.join(process.cwd(),'debug');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'alabama-traveler-information-systems.json'),text);}
function coords(raw,r){const lat=Number(first(r,['latitude','lat']));const lon=Number(first(r,['longitude','lon','lng']));if(Number.isFinite(lat)&&Number.isFinite(lon))return[lat,lon];const c=raw.geometry?.coordinates||r.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2)return[Number(c[1]),Number(c[0])];return[null,null];}
function deepValues(obj,matcher,out=[],depth=0){if(!obj||typeof obj!=='object'||depth>6)return out;for(const [k,v] of Object.entries(obj)){if(matcher.test(k)&&['string','number'].includes(typeof v)&&String(v).trim())out.push(v);if(v&&typeof v==='object')deepValues(v,matcher,out,depth+1);}return out;}
function pickMessage(r){const direct=first(r,['message','displayMessage','messageText','currentMessage','text','content','value','legend']);if(direct)return direct;return deepValues(r,/message|display|legend|text|content/i).find(v=>!/^https?:/i.test(String(v)))||'';}
async function fetchAlabama(){try{
 const {text}=await request(URL,{headers:{accept:'application/geo+json',origin:PAGE,referer:PAGE,authorization:'Bearer'}});saveDebug(text);const payload=JSON.parse(text);const records=recordsFromPayload(payload);
 const signs=records.map((raw,i)=>{const r=raw.properties||raw.attributes||raw;const kind=stripHtml(first(r,['type','deviceType','systemType','category','layer','travelerInformationSystemType','tisType'])||'');const msg=pickMessage(r);const messages=isNoMessage(msg)?[]:splitPages(msg);const [lat,lon]=coords(raw,r);const name=stripHtml(first(r,['name','description','location','title','deviceName'])||`Alabama device ${i+1}`);return{id:`AL-${first(r,['id','deviceId','systemId','objectId'])||i}`,state:'AL',agency:'ALDOT / ALGO Traffic',district:stripHtml(first(r,['region','district','area'])||kind),name,roadway:stripHtml(first(r,['roadway','route','roadName','routeName'])||''),direction:stripHtml(first(r,['direction','travelDirection'])||''),latitude:Number.isFinite(lat)?lat:null,longitude:Number.isFinite(lon)?lon:null,messages,imagePages:[],active:messages.length>0,online:!/(offline|disabled)/i.test(String(first(r,['status','operationalStatus'])||'')),demo:false,lastUpdated:first(r,['lastUpdated','updatedAt','modified']),sourceUrl:PAGE,signType:kind};}).filter(s=>/dms|vms|message|sign|traveler|billboard/i.test(`${s.signType} ${s.name}`)||s.messages.length);
 if(!signs.length)throw Error('ALGO feed loaded, but no DMS-like records were recognized; set ALGO_DEBUG=1 and inspect debug/alabama-traveler-information-systems.json');return{signs,status:{state:'AL',ok:true,mode:'live-geojson-endpoint',count:signs.length}};
 }catch(error){return{signs:[],status:{state:'AL',ok:false,mode:'unavailable',count:0,error:error.message}};}}
module.exports={fetchAlabama};
